### PR TITLE
Properly catch KeyError of deprecated file when loading a specific path

### LINKED ISSUE #55: Improve warning in case of deprecated file
If the wrapper fails to load a file because of a `KeyError`, we display a message informing the user that this probably occured because the file has been created by an old release version.

This only works if the user loads the entire file. If the user specifies a path to a deeper substructure of the stored file, by using `load('foo.h5', path='path/to/substructure')` or `load('foo.h5', 'path/to/substructure')`, the `KeyError` is caught by the `load` function and the message is not displayed.

We should improve the error handling so that the message is also displayed in this case.

### PR DESCRIPTION
**Pull request by mschmidt87**
This PR fixes #55 .

### CODE REVIEW

**Comment by mschmidt87** [comment]
I am not sure that to test for exactly. We are already testing that it is possible to load subparts of dictionaries with the `path` option (`test_write_and_load_with_label`) and this is what could possible be broken here.

**Comment by jakobj** [comment]
Hmm, maybe I misunderstood, but doesn't your change isolate the source of `KeyError` in `obj[path]` from `KeyError`s that might arise somewhere in the called function? One could check whether the `KeyError` is raised at the correct position. But this might be overkill.

**Comment by mschmidt87** [comment]
I think this is not really necessary.

**Comment by jakobj** [comment]
Very good :+1:

**Pull request merged**
